### ISSUE TITLE
ubuntu 20 / llvm14

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/workspace_automation#108]
```
FAILED: tools/resgen/resgen 
: && /usr/lib/llvm-18/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack tools/resgen/CMakeFiles/resgen.dir/src/main.cpp.o -o tools/resgen/resgen  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/utils/libutils.a  third_party/getopt/libgetopt.a  -Wl,-Bdynamic  -pthread  -ldl  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lc++abi
/usr/bin/ld: cannot find -lc++abi
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Looks lib libcxx-abi isn't getting installed in llvm-14 case.  Different error with llvm-18

**Comment by jwinarske** [comment]
```
[62/1512] Linking CXX executable tools/resgen/resgen
FAILED: tools/resgen/resgen 
: && /usr/lib/llvm-18/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack tools/resgen/CMakeFiles/resgen.dir/src/main.cpp.o -o tools/resgen/resgen  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/utils/libutils.a  third_party/getopt/libgetopt.a  -Wl,-Bdynamic  -pthread  -ldl  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lc++abi
/usr/bin/ld: cannot find -lc++abi
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[79/1512] Building CXX object third_party/glslang/tnt/glslang/CMakeFiles/glslang.dir/__/MachineIndependent/glslang_tab.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./flutter_workspace.py", line 2802, in <module>
    main()
  File "./flutter_workspace.py", line 351, in main
    setup_platforms(platforms, github_token, cookie_file, args.plex, args.enable, args.disable, args.enable_plugin,
  File "./flutter_workspace.py", line 2197, in setup_platforms
    setup_platform(dependency, git_token, cookie_file, plex, enable, disable, enable_plugin, disable_plugin,
  File "./flutter_workspace.py", line 1997, in setup_platform
    handle_post_cmds(runtime.get('post_cmds'))
  File "./flutter_workspace.py", line 1481, in handle_post_cmds
    handle_commands_obj(post_cmd, cwd)
  File "./flutter_workspace.py", line 1556, in handle_commands_obj
    subprocess.check_call(cmd_arr, cwd=cwd, env=local_env, shell=shell_)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--target', 'install', '--parallel']' returned non-zero exit status 1.
oem@TC4000432:~/workspace-automation$ find /usr -iname libc++*
/usr/share/doc/libc++abi1-14
/usr/share/doc/libc++-14-dev
/usr/share/doc/libc++1-14
/usr/share/doc/libc++abi-14-dev
/usr/share/lintian/overrides/libc++abi1-14
/usr/share/lintian/overrides/libc++-14-dev
/usr/share/lintian/overrides/libc++1-14
/usr/share/lintian/overrides/libc++abi-14-dev
/usr/lib/x86_64-linux-gnu/libc++abi.so.1.0
/usr/lib/x86_64-linux-gnu/libc++.so
/usr/lib/x86_64-linux-gnu/libc++.a
/usr/lib/x86_64-linux-gnu/libc++.so.1.0
/usr/lib/x86_64-linux-gnu/libc++.so.1
/usr/lib/x86_64-linux-gnu/libc++abi.so.1
/usr/lib/x86_64-linux-gnu/libc++abi.so
/usr/lib/llvm-14/lib/libc++abi.so.1.0
/usr/lib/llvm-14/lib/libc++.so
/usr/lib/llvm-14/lib/libc++abi.a
/usr/lib/llvm-14/lib/libc++.a
/usr/lib/llvm-14/lib/libc++experimental.a
/usr/lib/llvm-14/lib/libc++.so.1.0
/usr/lib/llvm-14/lib/libc++.so.1
/usr/lib/llvm-14/lib/libc++abi.so.1
/usr/lib/llvm-14/lib/libc++abi.so
```

**Comment by kerberjg** [comment]
Analysis:

Clang >= 16 uses `libc++-abi`, but Clang < 16 (including 14) uses `libstdc++-abi` instead ([source](https://github.com/toyota-connected/ivi-homescreen/blob/v2.0/cmake/compiler_clang.cmake#L74))

As per the log above, clang18 is executing instead of clang14 for some reason - turns out it's because flutter_workspace.py does not write PREFER_LLVM into setup_env.sh, resulting in CC/CXX in cmake defaulting to the wrong version.

Fixed by #110

**Comment by jwinarske** [comment]
@kerberjg  Still seeing the problem.

    PREFER_LLVM=14 ./flutter_workspace.py
    source ./setup_env.sh
    PREFER_LLVM=14 ./flutter_workspace.py --enable=filament

Generates

```
FAILED: tools/resgen/resgen 
: && /usr/lib/llvm-18/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack tools/resgen/CMakeFiles/resgen.dir/src/main.cpp.o -o tools/resgen/resgen  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/utils/libutils.a  third_party/getopt/libgetopt.a  -Wl,-Bdynamic  -pthread  -ldl  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lc++abi
/usr/bin/ld: cannot find -lc++abi
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kerberjg** [comment]
Alright, I’ll attempt to repro directly and will take it from there

**Comment by kerberjg** [comment]
@jwinarske Notes so far (will update this as I go)

- your logs still report `llvm-18` being used, currently my aim is to get that to repro
- repro is in progress (Ubuntu 20 is taking forever, it's running on an older machine) BUT I noticed the official LLVM install script does not install `libstdc++abi`, which could be part of the problem (but an easy fix)

**Comment by kerberjg** [comment]
Can't repro the above, `tools/resgen` is building correctly with `/usr/lib/llvm-14/bin/clang++` on a fresh workspace clone - looks like the above might be a local issue.

Alternatively try `git clean -xfdf`

However there's another issue building `spirv-tools`. Logs:

```
cmd: ['cmake', '--build', '.', '--config', 'Release', '--target', 'install', '--parallel']
[1488/1526] Linking CXX executable third_party/spirv-tools/tools/spirv-diff
FAILED: third_party/spirv-tools/tools/spirv-diff 
: && /usr/lib/llvm-14/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack third_party/spirv-tools/tools/CMakeFiles/spirv-diff.dir/util/flags.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-diff.dir/diff/diff.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-diff.dir/util/cli_consumer.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-diff.dir/io.cpp.o -o third_party/spirv-tools/tools/spirv-diff  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  third_party/spirv-tools/source/diff/libSPIRV-Tools-diff.a  third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a  third_party/spirv-tools/source/libSPIRV-Tools.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -lrt && :
/usr/bin/ld: /lib/x86_64-linux-gnu/libc++.a(memory.cpp.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1491/1526] Linking CXX executable third_party/spirv-tools/tools/spirv-dis
FAILED: third_party/spirv-tools/tools/spirv-dis 
: && /usr/lib/llvm-14/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack third_party/spirv-tools/tools/CMakeFiles/spirv-dis.dir/util/flags.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-dis.dir/dis/dis.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-dis.dir/io.cpp.o -o third_party/spirv-tools/tools/spirv-dis  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  third_party/spirv-tools/source/libSPIRV-Tools.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -lrt && :
/usr/bin/ld: /lib/x86_64-linux-gnu/libc++.a(memory.cpp.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1492/1526] Linking CXX executable third_party/spirv-tools/tools/spirv-val
FAILED: third_party/spirv-tools/tools/spirv-val 
: && /usr/lib/llvm-14/bin/clang++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections -Wl,-z,noexecstack third_party/spirv-tools/tools/CMakeFiles/spirv-val.dir/util/flags.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-val.dir/val/val.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-val.dir/util/cli_consumer.cpp.o third_party/spirv-tools/tools/CMakeFiles/spirv-val.dir/io.cpp.o -o third_party/spirv-tools/tools/spirv-val  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  third_party/spirv-tools/source/libSPIRV-Tools.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -lrt && :
/usr/bin/ld: /lib/x86_64-linux-gnu/libc++.a(memory.cpp.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1501/1526] Building CXX object third_party/perfetto/tnt/CMakeFiles/perfetto.dir/__/perfetto/perfetto.cc.o
ninja: build stopped: subcommand failed.

```

~Will try reproducing on Fedora 42 to see if it's an OS-specific issue~ (can't, Clang 14 is not supported on Fedora > 39 😔)

**Comment by kerberjg** [comment]
Found a workaround! ✨ 

The issue above is that `spirv-tools` is missing a `-pthread` in their CMakeLists.txt
Adding the following to `FILAMENT_CMAKE_ARGS` in `configs/filament.json` fixes it: `-DWEBGL_PTHREADS=ON -DWEBGL=OFF` (because of [this](https://github.com/google/filament/blob/f096c4d8de9f72e38f3ac1b0bbc176fb094994f7/CMakeLists.txt#L442C9-L442C24) - not the most proper solution, I know, but as a temporary fix it works)

With this `spirv-tools` builds successfully, but it should probably be reported as an issue in their repo.

**Comment by kerberjg** [comment]
`ivi-homescreen` fails to link with:

```
[179/179] Linking CXX executable shell/homescreen
FAILED: shell/homescreen 
: && /usr/lib/llvm-14/bin/clang++ -Os -DNDEBUG -Wl,--build-id=sha1    -static-libstdc++ -static-libgcc -stdlib=libstdc++ -lc -fuse-ld=lld -v -L/home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64 shell/CMakeFiles/ivi-homescreen.dir/app.cc.o shell/CMakeFiles/ivi-homescreen.dir/configuration/configuration.cc.o shell/CMakeFiles/ivi-homescreen.dir/engine.cc.o shell/CMakeFiles/ivi-homescreen.dir/libflutter_engine.cc.o shell/CMakeFiles/ivi-homescreen.dir/main.cc.o shell/CMakeFiles/ivi-homescreen.dir/timer.cc.o shell/CMakeFiles/ivi-homescreen.dir/view/flutter_view.cc.o shell/CMakeFiles/ivi-homescreen.dir/watchdog.cc.o shell/CMakeFiles/ivi-homescreen.dir/wayland/display.cc.o shell/CMakeFiles/ivi-homescreen.dir/wayland/window.cc.o shell/CMakeFiles/ivi-homescreen.dir/task_runner.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/wayland_egl/wayland_egl.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/wayland_egl/egl.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/gl_process_resolver.cc.o shell/CMakeFiles/ivi-homescreen.dir/platform/homescreen/platform_views/platform_views_handler.cc.o shell/CMakeFiles/ivi-homescreen.dir/platform/homescreen/platform_views/platform_view_touch.cc.o -o shell/homescreen -L/home/jamie/workspace-automation/app/ivi-homescreen/build -Wl,-rpath,/home/jamie/workspace-automation/app/ivi-homescreen/build:  third_party/flutter/libflutter.a  third_party/waypp/libwayland-gen.a  -ldl  shell/platform/homescreen/libplatform_homescreen.a  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libGLESv2.so  plugins/libplugins.a  plugins/desktop_window_linux/libplugin_desktop_window_linux.a  plugins/file_selector/libplugin_file_selector.a  plugins/go_router/libplugin_go_router.a  plugins/url_launcher/libplugin_url_launcher.a  plugins/rive_text/libplugin_rive_text.a  plugins/filament_view/libplugin_filament_view.a  shell/platform/homescreen/libplatform_homescreen.a  plugins/libplugins.a  plugins/desktop_window_linux/libplugin_desktop_window_linux.a  plugins/file_selector/libplugin_file_selector.a  plugins/go_router/libplugin_go_router.a  plugins/url_launcher/libplugin_url_launcher.a  plugins/rive_text/libplugin_rive_text.a  plugins/filament_view/libplugin_filament_view.a  third_party/waypp/libwayland-gen.a  /usr/lib/x86_64-linux-gnu/libwayland-cursor.so  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /usr/lib/x86_64-linux-gnu/libwayland-egl.so  /usr/lib/x86_64-linux-gnu/libwayland-client.so  plugins/common/libplugin_common.a  third_party/flutter/libflutter.a  plugins/common/libplugin_common_curl.a  /usr/lib/x86_64-linux-gnu/libcurl.so  -pthread  -Wl,-Bstatic  -lbackend  -lbluevk  -ldracodec  -lfilamat  -lfilameshio  -lgltfio_core  -limage  -lshaders  -luberarchive  -lviewer  -lbasis_transcoder  -lcamutils  -lfilabridge  -lfilament  -lgeometry  -libl  -limageio  -lmeshoptimizer  -lsmol-v  -luberzlib  -lvkshaders  -lcivetweb  -ltinyexr  -lfilaflat  -lfilament-iblprefilter  -lgltfio  -libl-lite  -lktxreader  -lmikktspace  -lpng  -lstb  -lutils  -lzstd  -Wl,-Bdynamic  -lz && :
Ubuntu clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-14/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-14/bin/ld.lld" -pie -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o shell/homescreen /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/10/crtbeginS.o -L/home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64 -L/home/jamie/workspace-automation/app/ivi-homescreen/build -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/llvm-14/bin/../lib -L/lib -L/usr/lib --build-id=sha1 -lc shell/CMakeFiles/ivi-homescreen.dir/app.cc.o shell/CMakeFiles/ivi-homescreen.dir/configuration/configuration.cc.o shell/CMakeFiles/ivi-homescreen.dir/engine.cc.o shell/CMakeFiles/ivi-homescreen.dir/libflutter_engine.cc.o shell/CMakeFiles/ivi-homescreen.dir/main.cc.o shell/CMakeFiles/ivi-homescreen.dir/timer.cc.o shell/CMakeFiles/ivi-homescreen.dir/view/flutter_view.cc.o shell/CMakeFiles/ivi-homescreen.dir/watchdog.cc.o shell/CMakeFiles/ivi-homescreen.dir/wayland/display.cc.o shell/CMakeFiles/ivi-homescreen.dir/wayland/window.cc.o shell/CMakeFiles/ivi-homescreen.dir/task_runner.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/wayland_egl/wayland_egl.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/wayland_egl/egl.cc.o shell/CMakeFiles/ivi-homescreen.dir/backend/gl_process_resolver.cc.o shell/CMakeFiles/ivi-homescreen.dir/platform/homescreen/platform_views/platform_views_handler.cc.o shell/CMakeFiles/ivi-homescreen.dir/platform/homescreen/platform_views/platform_view_touch.cc.o -rpath /home/jamie/workspace-automation/app/ivi-homescreen/build: third_party/flutter/libflutter.a third_party/waypp/libwayland-gen.a -ldl shell/platform/homescreen/libplatform_homescreen.a /usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/x86_64-linux-gnu/libGLESv2.so plugins/libplugins.a plugins/desktop_window_linux/libplugin_desktop_window_linux.a plugins/file_selector/libplugin_file_selector.a plugins/go_router/libplugin_go_router.a plugins/url_launcher/libplugin_url_launcher.a plugins/rive_text/libplugin_rive_text.a plugins/filament_view/libplugin_filament_view.a shell/platform/homescreen/libplatform_homescreen.a plugins/libplugins.a plugins/desktop_window_linux/libplugin_desktop_window_linux.a plugins/file_selector/libplugin_file_selector.a plugins/go_router/libplugin_go_router.a plugins/url_launcher/libplugin_url_launcher.a plugins/rive_text/libplugin_rive_text.a plugins/filament_view/libplugin_filament_view.a third_party/waypp/libwayland-gen.a /usr/lib/x86_64-linux-gnu/libwayland-cursor.so /usr/lib/x86_64-linux-gnu/libxkbcommon.so /usr/lib/x86_64-linux-gnu/libwayland-egl.so /usr/lib/x86_64-linux-gnu/libwayland-client.so plugins/common/libplugin_common.a third_party/flutter/libflutter.a plugins/common/libplugin_common_curl.a /usr/lib/x86_64-linux-gnu/libcurl.so -Bstatic -lbackend -lbluevk -ldracodec -lfilamat -lfilameshio -lgltfio_core -limage -lshaders -luberarchive -lviewer -lbasis_transcoder -lcamutils -lfilabridge -lfilament -lgeometry -libl -limageio -lmeshoptimizer -lsmol-v -luberzlib -lvkshaders -lcivetweb -ltinyexr -lfilaflat -lfilament-iblprefilter -lgltfio -libl-lite -lktxreader -lmikktspace -lpng -lstb -lutils -lzstd -Bdynamic -lz -Bstatic -lstdc++ -Bdynamic -lm -lgcc -lgcc_eh -lpthread -lc -lgcc -lgcc_eh /usr/lib/gcc/x86_64-linux-gnu/10/crtendS.o /lib/x86_64-linux-gnu/crtn.o
ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*)
>>> referenced by Animator.cpp
>>>               Animator.cpp.o:(filament::gltfio::Animator::Animator(filament::gltfio::FFilamentAsset const*, filament::gltfio::FFilamentInstance*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by ResourceLoader.cpp
>>>               ResourceLoader.cpp.o:(filament::gltfio::ResourceLoader::setConfiguration(filament::gltfio::ResourceConfiguration const&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by StbProvider.cpp
>>>               StbProvider.cpp.o:(filament::gltfio::StbProvider::pushTexture(unsigned char const*, unsigned long, char const*, filament::gltfio::TextureProvider::TextureFlags)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 6 more times

ld.lld: error: undefined symbol: std::bad_array_new_length::bad_array_new_length()
>>> referenced by Animator.cpp
>>>               Animator.cpp.o:(std::__throw_bad_array_new_length()) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> did you mean: std::bad_array_new_length::~bad_array_new_length()
>>> defined in: /usr/lib/gcc/x86_64-linux-gnu/10/libstdc++.a(bad_array_new.o)

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::allocator<char> const&)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 5 more times

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 5 more times

ld.lld: error: undefined symbol: std::__1::stoul(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long*, int)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::getNodeName(cgltf_node const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__shared_weak_count::__release_weak()
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::FAssetLoader::createPrimitives(cgltf_node const*, char const*, filament::gltfio::FFilamentAsset*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::FAssetLoader::FAssetLoader(filament::gltfio::AssetConfiguration const&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::shared_ptr<filament::gltfio::FFilamentAsset::SourceAsset>::~shared_ptr()) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 70 more times

ld.lld: error: undefined symbol: std::__1::__shared_weak_count::~__shared_weak_count()
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::__shared_ptr_pointer<filament::gltfio::FFilamentAsset::SourceAsset*, std::__1::shared_ptr<filament::gltfio::FFilamentAsset::SourceAsset>::__shared_ptr_default_delete<filament::gltfio::FFilamentAsset::SourceAsset, filament::gltfio::FFilamentAsset::SourceAsset>, std::__1::allocator<filament::gltfio::FFilamentAsset::SourceAsset> >::~__shared_ptr_pointer()) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(filament::gltfio::AssetLoaderExtended::AssetLoaderExtended(filament::gltfio::AssetConfigurationExtended const&, filament::Engine*, filament::gltfio::MaterialProvider&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::__shared_ptr_emplace<tsl::robin_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor> >, false, tsl::rh::power_of_two_growth_policy<2ul> >, std::__1::allocator<tsl::robin_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor> >, false, tsl::rh::power_of_two_growth_policy<2ul> > > >::~__shared_ptr_emplace()) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 20 more times

ld.lld: error: undefined symbol: std::__1::codecvt<char32_t, char, __mbstate_t>::~codecvt()
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>::~codecvt_utf8()) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::resize(unsigned long, char)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::wstring_convert<std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>, char32_t, std::__1::allocator<char32_t>, std::__1::allocator<char> >::to_bytes(char32_t const*, char32_t const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::wstring_convert<std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>, char32_t, std::__1::allocator<char32_t>, std::__1::allocator<char> >::to_bytes(char32_t const*, char32_t const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::wstring_convert<std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>, char32_t, std::__1::allocator<char32_t>, std::__1::allocator<char> >::to_bytes(char32_t const*, char32_t const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced 12 more times

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::wstring_convert<std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>, char32_t, std::__1::allocator<char32_t>, std::__1::allocator<char> >::to_bytes(char32_t const*, char32_t const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by options.cc
>>>               options.cc.o:(draco::Options::GetString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libdracodec.a
>>> referenced by options.cc
>>>               options.cc.o:(draco::Options::GetString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libdracodec.a
>>> referenced 77 more times

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::enable_if<__is_cpp17_forward_iterator<char const*>::value, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append<char const*>(char const*, char const*)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__next_prime(unsigned long)
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&>, std::__1::tuple<> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&>&&, std::__1::tuple<>&&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<utils::Entity, std::__1::allocator<utils::Entity> > > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&>, std::__1::tuple<> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&>&&, std::__1::tuple<>&&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by point_attribute.cc
>>>               point_attribute.cc.o:(std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> >, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> >, std::__1::__unordered_map_hasher<std::__1::array<unsigned int, 1ul>, std::__1::__hash_value_type<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> >, draco::HashArray<std::__1::array<unsigned int, 1ul> >, std::__1::equal_to<std::__1::array<unsigned int, 1ul> >, true>, std::__1::__unordered_map_equal<std::__1::array<unsigned int, 1ul>, std::__1::__hash_value_type<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> >, std::__1::equal_to<std::__1::array<unsigned int, 1ul> >, draco::HashArray<std::__1::array<unsigned int, 1ul> >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> > > >::__emplace_unique_key_args<std::__1::array<unsigned int, 1ul>, std::__1::pair<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> > >(std::__1::array<unsigned int, 1ul> const&, std::__1::pair<std::__1::array<unsigned int, 1ul>, draco::IndexType<unsigned int, draco::AttributeValueIndex_tag_type_> >&&)) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libdracodec.a
>>> referenced 119 more times

ld.lld: error: undefined symbol: typeinfo for std::__1::__shared_weak_count
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(typeinfo for std::__1::__shared_ptr_pointer<filament::gltfio::FFilamentAsset::SourceAsset*, std::__1::shared_ptr<filament::gltfio::FFilamentAsset::SourceAsset>::__shared_ptr_default_delete<filament::gltfio::FFilamentAsset::SourceAsset, filament::gltfio::FFilamentAsset::SourceAsset>, std::__1::allocator<filament::gltfio::FFilamentAsset::SourceAsset> >) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(typeinfo for std::__1::__shared_ptr_emplace<tsl::robin_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor> >, false, tsl::rh::power_of_two_growth_policy<2ul> >, std::__1::allocator<tsl::robin_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, filament::backend::BufferDescriptor> >, false, tsl::rh::power_of_two_growth_policy<2ul> > > >) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a
>>> referenced by LinearImage.cpp
>>>               LinearImage.cpp.o:(typeinfo for std::__1::__shared_ptr_pointer<float*, std::__1::default_delete<float []>, std::__1::allocator<float> >) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libimage.a
>>> referenced 7 more times

ld.lld: error: undefined symbol: std::__1::locale::facet::__on_zero_shared()
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_out(__mbstate_t&, char32_t const*, char32_t const*, char32_t const*&, char*, char*, char*&) const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_in(__mbstate_t&, char const*, char const*, char const*&, char32_t*, char32_t*, char32_t*&) const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_unshift(__mbstate_t&, char*, char*, char*&) const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_encoding() const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_always_noconv() const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: undefined symbol: std::__1::__codecvt_utf8<char32_t>::do_length(__mbstate_t&, char const*, char const*, unsigned long) const
>>> referenced by AssetLoader.cpp
>>>               AssetLoader.cpp.o:(vtable for std::__1::codecvt_utf8<char32_t, 1114111ul, (std::__1::codecvt_mode)0>) in archive /home/jamie/workspace-automation/app/filament/cmake-build-release/staging/release/lib/x86_64/libgltfio_core.a

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

~Can't figure out what that is, wonder if that maybe should also be an external issue filed with google/filament~
Nope, that's an issue with link arguments in `ivi-homescreen/cmake/compiler_clang.cmake` (see [apache/doris#20084](https://github.com/apache/doris/issues/20084#issuecomment-1886182378)), testing a fix...

**Comment by jwinarske** [comment]
@kerberjg changing the conditional check from 16 to 14 resolves the problem:
https://github.com/toyota-connected/ivi-homescreen/blob/v2.0/cmake/compiler_clang.cmake#L74

This was added to handle Yocto limitation before llvm-14 was backported to dunfell.

**Comment by kerberjg** [comment]
@jwinarske I see! My fix was gonna be this:

```
if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 16)
    message(STATUS "stdlib ................. libc++")
    set(STDLIB c++)
else ()
    message(STATUS "stdlib ................. libstdc++")
    set(STDLIB stdc++)
endif ()

target_compile_options(toolchain INTERFACE -stdlib=lib${STDLIB} -isystem"${LLVM_INCLUDE_DIRS}/c++/v1/")

if (ENABLE_STATIC_LINK)
    target_link_options(toolchain INTERFACE -static-libstdc++ -static-libgcc -stdlib=lib${STDLIB} -lc -l${STDLIB} -fuse-ld=lld -v)
else ()
    target_link_options(toolchain INTERFACE -stdlib=lib${STDLIB} -lc -l${STDLIB} -fuse-ld=lld -v)
endif ()
```

But I haven't tested it since I couldn't push to `ivi-homescreen`

**Comment by jwinarske** [comment]
@kerberjg I pulled fix into meta-flutter dunfell candidate branch and the first CI is passing.  Once that merges then I can move to rolling Filament to 1.60.1.

**Comment by kerberjg** [comment]
@jwinarske Nice! Now I'm getting a compile error on filament_view, so that's most likely going to fail, but I'll fix it a bit later in the day:

```
In file included from /home/jamie/workspace-automation/app/ivi-homescreen-plugins/plugins/filament_view/core/utils/hdr_loader.cc:16:
/home/jamie/workspace-automation/app/ivi-homescreen-plugins/plugins/filament_view/core/utils/hdr_loader.h:31:26: error: reference to incomplete type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char>>') could not bind to an lvalue of type 'const char[11]'
      const std::string& name = "memory.hdr"
                         ^      ~~~~~~~~~~~~
```

**Comment by jwinarske** [comment]
x86_64 and aarch64 are fine/passing.  Hitting segfaults in dunfell llvm-14 arm when linking filament source; currently testing without Filament LTO.

**Comment by jwinarske** [comment]
disabling LTO enables `arm` build to pass (not segfault at link time).  Dunfell x86_64, aarch64, and arm are passing with llvm-14 + filament 1.54.  I merged changes to meta-flutter dunfell.

Still having some quirks on workspace automation using `PREFER_LLVM=14 ./flutter_workspace.py --enable=filament
`

**Comment by jwinarske** [comment]
changes required for dunfell:
https://github.com/meta-flutter/meta-flutter/pull/672
https://github.com/jwinarske/meta-vulkan/pull/26
https://github.com/jwinarske/meta-vulkan/pull/27

**Comment by jwinarske** [comment]
Closing since all workspace automation issues have been quantified/addressed, and meta-flutter dunfell builds with filament _view is passing.
